name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.1", "7.2", "7.3", "7.4"]
        service: [php-fpm]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        PHP_VERSION: ${{ matrix.php_version }}
        BUILD_SERVICE: ${{ matrix.service }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: bash build-image.sh
